*** Variables ***
# Connections to Oracle 12
&{ORACLE12}    HOST=ORACLE12_HOST    SID=ORACLE12_SID    PORT=ORACLE12_PORT    USER=ORACLE12_USER  PASSWORD=ORACLE12_PASSWORD
# Connections to Oracle 19
&{ORACLE19}    HOST=ORACLE19_HOST    SID=ORACLE19_SID    PORT=ORACLE19_PORT    USER=ORACLE19_USER  PASSWORD=ORACLE19_PASSWORD

# Connections to SQLIGHT
&{SQLIGHT}     DATABASE="./Chinook.db"
