# For more details on the format and content:
# https://github.com/robocorp/rcc/blob/master/docs/recipes.md#what-is-in-condayaml
# Tip: Adding a link to the release notes of the packages helps maintenance and security.

channels:
  - conda-forge

dependencies:
  - python=3.10.12                    # https://pyreadiness.org/3.10
  - pip=23.2.1                        # https://pip.pypa.io/en/stable/news
  - robocorp-truststore=0.8.0         # https://pypi.org/project/robocorp-truststore/
  - pip:
    - rpaframework==28.6.0                        # https://rpaframework.org/releasenotes.html
    - oracledb==2.2.1                             # https://pypi.org/project/oracledb/
    - robotframework-databaselibrary==1.4.4       # https://pypi.org/project/robotframework-databaselibrary/
    - robotframework-seleniumlibrary==6.5.0       # https://robotframework.org/SeleniumLibrary/SeleniumLibrary.html
    - allure-robotframework==2.13.5               # https://pypi.org/project/allure-robotframework/
    - robotframework-requests==0.9.7              # https://www.piwheels.org/project/robotframework-requests/
    - pandas==2.2.2                               # https://pypi.org/project/pandas/
    - robotframework-mockserver==0.0.7            # https://pypi.org/project/robotframework-mockserver/








