UFFS:
  type:
    - db
    - csv
  db:
    schema: dbo
    table_name:
      - local_table_1
      - local_table_2
  csv:
    csv_test_source:
      source_file_path: ./test_data/e2e/uffs/csv/test_data.csv
  MDM:
    host: http://localhost:1080/
    path: 
    - /mdm_api_1
    - /mdm_api_2
    - /mdm_api_3
    query: 
    - query_1
    - query_2
    - query_3
  ODS:
    host: http://localhost:1080/
    path: 
    - /ods_api_1
    - /ods_api_2
    - /ods_api_3
    query: 
    - query_1
    - query_2
    - query_3